language: node_js
node_js:
- '8'
- '10'
cache: yarn
script:
- npm run ci
deploy:
  provider: npm
  skip_cleanup: true
  email: rplan-ci@actano.de
  on:
    tags: true
    repo: actano/mocha-junit
    node: '8'
  api_key:
    secure: WMonPI8wPyUlyg2oyJbxYX7rR5GG5GHjkQSTUGEtsUWFfaG9W3hrwiqz+JzKy246L/49bvHqRcN5Ovkr9+lReqH4B38+/8GwgiEvRB5frmch7itddmcmzts08HjUb/t1F1dYjc/hBMNO9fstdJNsvGP0jpH65GPb6p/FxviMNHn70yBmHgOYY4rsjxIeDvN8HtUWJ86DuuHXmuHzlXXIxuB5LgxqAUHUjy5SpqdNnXru0XxNAsC1jHctF2xVn7Q9I/66EgfaQMVxGvKMjTy6x8hMIpTtfhGpCK/Z5ALcCGNddiingOQYICAupUoETLzYYwKIzbtIfnBsm1AvReeZ++zUAwf9j6eROKdNh9h+iUn0nOxggSmPeFFvzKtXqXf0C2VmhxSKcDzD6L2h72fkH0IfgMETJX0NtNgGKB7W0VKMjwws+Oqatm2ahhYr0aYF4A8ik0q7KqjXVx27h7vkRSc7jqjwAGq4pLi6uD225mO1dmR6G+dunxx+WyKMEiXd0fztFJAgrHLDWfQh1qOlCXvuZoILtShvninRSE2fuiTSXL5TPMUiS53ynd2odNUF4uKRgfHpk+11u0Ojs92aAh/WZqvTs+ENCXjsizDTY0bN0u6jDrfDIR7X8LeKwvEQuntbEkzAtc02w2qOsaBsS2tfVzap5sQAWvEowbjkVss=
